[package]
name = "i3ext"
version = "0.1.0"
authors = ["tone <tony.y.gong@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i3ipc = "0.10"
anyhow = "1.0"
argh = "0.1"
log = "0.4"
simple_logger = "1.11"
